/*
 ********************* < CUSTOM MEMORY ALLOCATOR > ****************************
 ******************************************************************************
 * @file           : main.c
 * @author         : Abhinav Lal
 * @brief          : Main program body generated by IDE as an empty project
 ******************************************************************************
 */

#include "custom_allocator.h"

int main(void)
{
	init_custom_memory();

	unsigned int *myptr1 = custom_malloc(5);
	for(int i = 0; i < 5; i++)
	{
		myptr1[i] = 111;
	}

	unsigned int *myptr2 = custom_malloc(3);
	for(int i = 0; i < 3; i++)
	{
		myptr2[i] = 222;
	}

	unsigned int *myptr3 = custom_malloc(2);
	for(int i = 0; i < 2; i++)
	{
		myptr3[i] = 333;
	}

	custom_free(myptr1);

	unsigned int *myptr4 = custom_malloc(5);
	for(int i = 0; i < 5; i++)
	{
		myptr4[i] = 444;
	}

	custom_free(myptr3);

	unsigned int *myptr5 = custom_malloc(1);
	myptr5[0] = 555;

	return 0;
}
